let crests=[],drops=[],tideSeed=36;
function setup(){createCanvas(windowWidth,windowHeight);pixelDensity(1);colorMode(HSB,360,100,100,1);resetTide()}
function resetTide(){randomSeed(tideSeed);noiseSeed(tideSeed);crests=[];drops=[];for(let i=0;i<9;i++)crests.push({y:height*(.22+i*.075),amp:random(18,70),len:random(.004,.013),phase:random(TAU),speed:random(.015,.045),weight:random(2,8)})}
function draw(){background(42,18,91);paperGrain();sunAndBoats();drawWaves();drawFoam()}
function drawWaves(){const px=pointerX(),py=pointerY();for(let i=crests.length-1;i>=0;i--){const c=crests[i],influence=map(dist(px,py,width*.45,c.y),0,width,1.7,.35,true),baseHue=lerp(203,218,i/crests.length);noFill();for(let band=0;band<5;band++){stroke(baseHue+band*4,72-band*8,34+band*10,.92-band*.1);strokeWeight(c.weight+band*1.6);beginShape();for(let x=-60;x<=width+60;x+=10){const d=abs(x-px),pull=exp(-d*.01)*sin((py-c.y)*.018)*110,curl=sin(x*c.len+c.phase+frameCount*c.speed)*c.amp*influence,chop=noise(x*.012,i*3,frameCount*.015)*46;curveVertex(x,c.y+i*8+curl+chop+pull*(1-band*.14)+band*12)}endShape()}}}
function drawFoam(){if(mouseIsPressed||touches.length){const px=pointerX(),py=pointerY();for(let i=0;i<8;i++)drops.push({x:px+random(-24,24),y:py+random(-18,18),vx:random(-2,2),vy:random(-7,-1),life:80})}noStroke();for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.x+=d.vx+sin(frameCount*.05+d.y)*.8;d.y+=d.vy;d.vy+=.11;d.life--;fill(39,22,99,d.life/80);circle(d.x,d.y,map(d.life,80,0,10,1));if(d.life<=0)drops.splice(i,1)}}
function sunAndBoats(){noStroke();fill(31,70,94,.95);circle(width*.78,height*.22,min(width,height)*.12);fill(27,62,24,.9);for(let i=0;i<3;i++){const x=width*(.18+i*.18)+sin(frameCount*.02+i)*18,y=height*(.72+i*.04);push();translate(x,y);rotate(sin(frameCount*.025+i)*.08);beginShape();vertex(-46,0);vertex(42,0);vertex(20,14);vertex(-34,13);endShape(CLOSE);pop()}}
function paperGrain(){stroke(36,20,30,.045);strokeWeight(1);for(let i=0;i<120;i++)point(random(width),random(height))}
function pointerX(){return touches.length?touches[0].x:(mouseX||width*.52)}function pointerY(){return touches.length?touches[0].y:(mouseY||height*.54)}function mousePressed(){tideSeed++;resetTide()}function touchStarted(){tideSeed++;resetTide();return false}function windowResized(){resizeCanvas(windowWidth,windowHeight);resetTide()}
